source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'HDTool_Example' do
  pod 'HDTool', :path => '../'

  target 'HDTool_Tests' do
    inherit! :search_paths
  end
  
end
